---
title: "Ejercicio práctico Rmarkdown"
author:
    - names: "Juan Manuel Barba Reyes"
date: "`r Sys.Date()`" 
output: 
    distill::distill_article:
        highlight: kate
        code_folding: false  
        toc: true     
        toc_depth: 3
        css: styles.css         
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE)

# Cargar los paquetes necesarios
library(tidyr)
library(dplyr)

# Cargar los datos
data <- read.csv("/home/path/FC2516/data/top10s.csv")

```

# Informe hits de Spotify 2010-2019

## Datos

Top Spotify Songs 2010-2019

<https://www.kaggle.com/datasets/leonardopena/top-spotify-songs-from-20102019-by-year/>

## Artistas con más éxitos

```{r top_artists}

data %>% dplyr::count(artist) %>% arrange(desc(n)) %>% head()

 artist  n
1    Katy Perry 17
2 Justin Bieber 16
3      Maroon 5 15
4       Rihanna 15
5     Lady Gaga 14
6    Bruno Mars 13

```

## Estilos con más éxitos

```{r top_genres}

data %>% dplyr::count(top.genre) %>% arrange(desc(n)) %>% head()

top.genre   n
1     dance pop 327
2           pop  60
3  canadian pop  34
4 barbadian pop  15
5      boy band  15
6    electropop  13

```

## Tendencia de la duración de los hits

```{r duration_trend, fig.width=8, fig.height=6}

plot(dur ~ year, data = data)
abline(lm(dur ~ year, data = data))

```

## Zenodo DOI:

https://doi.org/10.5281/zenodo.14838051
10.5281/zenodo.14838051
